### ISSUE TITLE
布局边界bug

### ISSUE THREAD

**Issue by esmark-developer** [LillteZheng/FlowHelper#10]
![image](https://user-images.githubusercontent.com/19761796/77273725-3cb99400-6cef-11ea-9364-1d7de7efaf40.png)

我在约束布局中如上图布局，TabFlowLayout与ViewPager配合使用；
当tab较多时，滑动至最后1个tab时，最后一个tab无法显示；实际最后一个tab存在，但是在右边界的外部；
如上图，TabFlowLayout的右边界是iv_workbench_rank的左侧，显示中TabFlowLayout的右边界也确实如此，但是tab的排布和加载实际已经到了iv_workbench_rank的位置，所以无法显示

**Comment by LillteZheng** [comment]
你的image 看不到，可以把现象和关键代码传到上来，或者百度云

**Comment by LillteZheng** [comment]
你这个是 ConstraintLayout 的问题，把宽度设置为 0dp，多练习 ConstraintLayout 啊

**Comment by esmark-developer** [comment]
约束布局宽度是该设置为0dp，但是TabFlowLayout就没有选择指示了，而且不会滚动…我还以为TabFlowLayout的宽必须是wrap

**Comment by LillteZheng** [comment]
嗯嗯，宽度问题我在文档写一下，感谢提醒

**Comment by esmark-developer** [comment]
辛苦了，我一直用的Flyco大佬的TabLayout，后来切了AndroidX，你的库非常棒，我会和我同事一起支持你

**Comment by esmark-developer** [comment]
兄弟，你的描述我还是没太看明白…

**Comment by LillteZheng** [comment]
在  ConstraintLayout 中，0dp 表示确定大小的意思。但你得做好约束啊。比如你的问题。那就应该是
  app:layout_constraintStart_toStartOf="parent" 左对齐父控件
 app:layout_constraintEnd_toStartOf="@+id/iv_workbench_rank" 右对齐你的控件

这样，TabFlowLayout 才能拿到确定宽度，不然就会一直为 0 啊。
再看看呢

**Comment by LillteZheng** [comment]
xml 代码参考：
    <com.zhengsr.tablib.view.flow.TabFlowLayout
        android:id="@+id/rectflow"
        android:layout_width="0dp"
        android:layout_marginTop="5dp"
        app:tab_type="rect"
        app:tab_color="@color/colorPrimary"
        app:tab_height="3dp"
        app:tab_width="20dp"
        app:tab_margin_b="3dp"
        app:tab_scale_factor="1.2"
        app:tab_item_autoScale="true"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintEnd_toStartOf="@id/test"
        app:layout_constraintStart_toStartOf="parent"
        android:layout_height="wrap_content"/>

    <ImageView
        android:id="@+id/test"
        app:layout_constraintTop_toTopOf="parent"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@mipmap/ic_launcher"
        app:layout_constraintEnd_toEndOf="parent"
        />
这样就可以啦，我这边运行没问题，你可以参考一下
