### ISSUE TITLE
发现在网络请求后再设置setVisualCount就无效了

### ISSUE THREAD

**Issue by mengbixiusi** [LillteZheng/FlowHelper#12]
将同样的代码放到请求外可以居中, 网络请求后再设置就还是左边了

**Comment by LillteZheng** [comment]
setVisualCount 需要你在配置 tabadatper 之前就得设置，不然父控件无法知道是需要均分的，所以默认左边的；你可以网络请求成功后，再去设置  tabflowLayout 就可以了

**Comment by mengbixiusi** [comment]
我有试过, 没作用. 感觉不是它引起的. 因为如果我在网络请求外设置的话,哪怕setVisualCount在配置 tabadatper 之后, 也是可以均分的.... 很奇怪

**Comment by LillteZheng** [comment]
具体代码发上来呢

**Comment by mengbixiusi** [comment]
List listTab = new ArrayList();
                        for (int i = 0; i < 2; i++) {
                            String mTab = "";
                            String mOriginal = "全部";
                            for (int j = 0; j < mOriginal.length(); j++) {

                                mTab = mTab + mOriginal.charAt(j) + "\n";
                            }
                            listTab.add(mTab);
                        }
                        adapter = new CommonTabPagerAdapter(getAttachActivity().getSupportFragmentManager()
                                , listTab.size(), listTab, getAttachActivity());
                        adapter.setListener(TestHomeFragment.this);
                        viewpager.setAdapter(adapter);
                        viewpager.setId(viewpager.getCurrentItem());

                        tabLayout.setViewPager(viewpager);
                        tabLayout.setVisualCount(listTab.size());
                        tabLayout.setAdapter(new TabFlowAdapter<String>(R.layout.item_tab_text, listTab) {
                            @Override
                            public void onItemSelectState(View view, boolean isSelected) {
                                super.onItemSelectState(view, isSelected);
                                //选中时，可以改变不同颜色，如果你的background 为 selector，可以不写这个
                                if (isSelected) {
                                    setTextColor(view, R.id.item_text, getResources().getColor(R.color.black));
                                } else {
                                    setTextColor(view, R.id.item_text, getResources().getColor(R.color.textColorHint));
                                }
                            }

                            @Override
                            public void onItemClick(View view, String data, int position) {
                                super.onItemClick(view, data, position);
                                viewpager.setCurrentItem(position);

                            }

                            @Override
                            public void bindView(View view, String data, int position) {
                                /**
                                 * 绑定数据，可以使用 setText(..) 等快捷方式，也可以视同 view.findViewById()
                                 * 同时，当你的子控件需要点击事件时，可以通过  addChildrenClick() 注册事件，
                                 * 然后重写 onItemChildClick(..) 即可拿到事件，否则就自己写。
                                 * 自己的点击和长按不需要注册
                                 */
                                setText(view, R.id.item_text, data)
                                ;
//                if (position == 0){
//                    setVisible(view,R.id.item_msg,true);
//                }

                                // 注册子控件的点击事件
                                //addChildrenClick(view,R.id.item_text,position);
                                //注册子控件的长按事件
                                //addChildrenLongClick(view,R.id.item_text,position);

                            }
                        });

//viewpager的 adapter比较多,不方便发

**Comment by LillteZheng** [comment]
嗯，貌似没看到你用了网络请求，不过我晚上也回去看一下

**Comment by mengbixiusi** [comment]
哦,我是单独拿出来的. 方便测试. 好的, 你有时间看下吧, 麻烦大佬了

**Comment by mengbixiusi** [comment]
刚试了一下,
new Thread(new Runnable() {
            @Override
            public void run() {
                getAttachActivity().runOnUiThread(()->{
                    
                });
            }
        }).start();
开启子线程再转到ui来执行,就不行了.

**Comment by LillteZheng** [comment]
你的tabflowlayout是不是设置成 wrap_content 了？设置成 match_parent 或者固定宽度试试，然后再更新一下最新版

**Comment by mengbixiusi** [comment]
不知我哪里做的不对, 最新版和match parent无效.
这个应该是因为控件先绘制了，我试了试数据获取后再初始化控件,可以做到居中.
是不是因为tabflowlayout没有刷新或者重新绘制的机制导致的

**Comment by LillteZheng** [comment]
adapter.notifydatachange() 可以刷新，试试呢，我早上也试一下，或者你下载demo的网络测试那里可以看到是居中的

**Comment by mengbixiusi** [comment]
辛苦了,可能是我代码的问题. 
我只能使用ViewStub延迟初始化,暂时这么解决了.
