### ISSUE TITLE
TabFlowLayout选中和未选中

### ISSUE THREAD

**Issue by AndMy** [LillteZheng/FlowHelper#14]
TabFlowLayout选中时字体加粗和字号变大
TabFlowLayout未选中时字体不加粗和字号不变大
用哪个属性啊

**Comment by LillteZheng** [comment]
没有加粗功能，设置自动缩放就行了 tab_item_autoScale = true

**Comment by AndMy** [comment]
> 
> 
> 没有加粗功能，设置自动缩放就行了 tab_item_autoScale = true

设置这个两个属性tab_item_autoScale = true和app:tab_scale_factor="1.25"的话
首次默认进去的字体的粗细比切换之后的字体细一点，切换一次后感觉变粗了
这个问题是我这边操作不当造成的么
