### ISSUE TITLE
请大佬看下这个问题  Cannot make calls to a recycled instance!

### ISSUE THREAD

**Issue by solomon2** [LillteZheng/FlowHelper#16]
# main(2)

java.lang.RuntimeException

Cannot make calls to a recycled instance!

1 android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:768)
2 com.zhengsr.tablib.view.action.BaseAction.configAttrs(BaseAction.java:552)
3 com.zhengsr.tablib.view.flow.TabFlowLayout.chooseTabTpye(TabFlowLayout.java:186)
4 com.zhengsr.tablib.view.flow.TabFlowLayout.setTabBean(TabFlowLayout.java:645)
5 net.xx.CompetitionFragment.initFragment(CompetitionFragment.java:242)
6 net.xx.CompetitionFragment.onViewCreated(CompetitionFragment.java:82)
7 androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:892)
8 androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
9 androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
10 androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
11 androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
12 androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
13 androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
14 androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
15 androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
16 androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
17 androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
18 androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
19 androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
20 android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
21 android.app.Activity.performStart(Activity.java:7924)
22 android.app.ActivityThread.handleStartActivity(ActivityThread.java:3332)
23 android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
24 android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
25 android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
26 android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
27 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
28 android.os.Handler.dispatchMessage(Handler.java:107)
29 android.os.Looper.loop(Looper.java:224)
30 android.app.ActivityThread.main(ActivityThread.java:7551)
31 java.lang.reflect.Method.invoke(Native Method)
32 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
33 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by LillteZheng** [comment]
试一下最新的v1.24。
去掉自定义view的 recycle 判断了
