### ISSUE TITLE
设置tab_color 无效

### ISSUE THREAD

**Issue by Hn1993** [LillteZheng/FlowHelper#18]
<com.zhengsr.tablib.view.flow.TabFlowLayout
            android:id="@+id/main_tab"
            android:layout_width="wrap_content"
            android:background="@color/white"
            app:tab_type="rect"
            app:tab_color="@color/color_base_color"
            app:tab_height="@dimen/px5"
            app:tab_margin_t="@dimen/px5"
            app:tab_item_autoScale="true"
            app:tab_scale_factor="1.22"
            android:paddingBottom="@dimen/px30"
            android:layout_height="wrap_content" />

这个是使用的代码  下面是效果截图        <color name="color_base_color">#3874F6</color>    color_base_color 是蓝色效果
![Uploading 1605255866(1).jpg…]()

**Comment by Hn1993** [comment]
我直接下载demo   app:tab_color 也无效...

**Comment by LillteZheng** [comment]
> 我直接下载demo app:tab_color 也无效...

demo 中我记得也有tab_color 的例子，看看有什么不同呢

**Comment by Hn1993** [comment]
没什么不同，我直接改demo中的色值也不行...不知道哪里的问题

**Comment by LillteZheng** [comment]
感谢提醒，已修复，更新到v1.27即可
