### ISSUE TITLE
默认选择

### ISSUE THREAD

**Issue by liuzining925** [LillteZheng/FlowHelper#19]
如何设置默认选择的条目tabflow.setDefaultPosition(0);不生效

**Comment by littonishir** [comment]
override fun bindView(view: View?, data: String?, position: Int) {
                setText(view, R.id.item_text, data).addChildrenClick(view,R.id.item_text,position)
                if (position == 0){
                    setTextColor(view, R.id.item_text, Color.WHITE);
                }
            }

**Comment by LillteZheng** [comment]
未说明啥
