### ISSUE TITLE
tablibx中点击文本切换tab时，tab横线会来回摆动

### ISSUE THREAD

**Issue by caoyy** [LillteZheng/FlowHelper#20]
tablibx中在点击文本切换tab时，tab下划线会来回快速摆动后再停在对应的tab上。

**Comment by littonishir** [comment]
override fun bindView(view: View?, data: String?, position: Int) {
                setText(view, R.id.item_text, data).addChildrenClick(view,R.id.item_text,position)
            }

            override fun onItemChildClick(childView: View?, position: Int) {
                super.onItemChildClick(childView, position)
                viewpager.currentItem = position

            }
这样写可以不摆动

**Comment by LillteZheng** [comment]
> tablibx中在点击文本切换tab时，tab下划线会来回快速摆动后再停在对应的tab上。

更新到v1.28 即可
