### ISSUE TITLE
notifyDataChanged 导致tab_visual_count设置的文字显示错乱

### ISSUE THREAD

**Issue by qingyinz** [LillteZheng/FlowHelper#23]
进入页面的时候数据显示是正常的
![QQ图片20210608175540](https://user-images.githubusercontent.com/30486512/121165524-eba9a780-c882-11eb-8df3-66db039b33a1.jpg)

使用           flowLayout.getAdapter().notifyDataChanged();
![QQ图片247](https://user-images.githubusercontent.com/30486512/121165575-f401e280-c882-11eb-97f0-f1843b8569ef.jpg)

文字会全部到左边来，下方横线正常
关键代码
`mTitle = Arrays.asList(String.format("未盘(%s)",inventorySubListBean.getCheckingNum()),
                String.format("已盘(%s)",inventorySubListBean.getCheckedNum()),
                String.format("新增资产(%s)",inventorySubListBean.getNewNum()));
 private void rectFlow() {
        //设置数据，这里以 setAdapter 的形式
        flowLayout.setAdapter(new TabFlowAdapter<String>(R.layout.item_msg, mTitle) {
            @Override
            public void onItemSelectState(View view, boolean isSelected) {
                super.onItemSelectState(view, isSelected);
                //选中时，可以改变不同颜色，如果你的background 为 selector，可以不写这个
                if (isSelected) {
                    setTextColor(view, R.id.item_text, Color.BLUE);
                } else {
                    setTextColor(view, R.id.item_text, getResources().getColor(R.color.unselect));
                    current = 1;
                    updateAll(current, size, assetsStatus, "resh");
                }
            }

            @Override
            public void onItemClick(View view, String data, int position) {
                super.onItemClick(view, data, position);
                switch (position) {
                    case 0:
                        assetsStatus="未盘";
                        break;
                    case 1:
                        assetsStatus="已盘";
                        break;
                    case 2:
                        assetsStatus="新增资产";
                        break;
                }
            }

            @Override
            public void bindView(View view, String data, int position) {
                /**
                 * 绑定数据，可以使用 setText(..) 等快捷方式，也可以视同 view.findViewById()
                 * 同时，当你的子控件需要点击事件时，可以通过  addChildrenClick() 注册事件，
                 * 然后重写 onItemChildClick(..) 即可拿到事件，否则就自己写。
                 * 自己的点击和长按不需要注册
                 */
                setText(view, R.id.item_text, data)
                        .setTextColor(view, R.id.item_text, getResources().getColor(R.color.unselect));

            }
        });
    }`
`    <com.zhengsr.tablib.view.flow.TabFlowLayout
        android:id="@+id/rectflow"
        android:layout_width="match_parent"
        android:layout_height="40dp"
        android:layout_marginTop="5dp"
        android:background="#FFFFFF"
        app:tab_color="@color/colorToolBar"
        app:tab_height="3dp"
        app:tab_item_autoScale="true"
        app:tab_margin_t="6dp"
        app:tab_scale_factor="1.3"
        app:tab_type="rect"
        app:tab_visual_count="3"
 />`
`<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <TextView
        android:id="@+id/item_text"
        android:layout_width="wrap_content"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        tools:text="测试"
        android:paddingTop="6dp"
        android:paddingBottom="6dp"
        android:paddingStart="12dp"
        android:paddingEnd="12dp"
        android:textSize="14sp"
        android:gravity="center"
        android:textColor="@color/unselect"
        android:layout_height="wrap_content"/>

    <TextView
        android:layout_width="5dp"
        android:layout_height="5dp"
        android:gravity="center"
        android:textSize="8dp"
        android:background="@drawable/shape_red_radius"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        android:layout_margin="5dp"
        android:visibility="gone"
        />

</android.support.constraint.ConstraintLayout>`

**Comment by LillteZheng** [comment]
更新到v1.30
