### ISSUE TITLE
tab标签选项较多会出现显示错乱

### ISSUE THREAD

**Issue by qingyinz** [LillteZheng/FlowHelper#24]
1.30版本
数量少时显示正常，多的时候就会出现tab横线位置不跟随，或者跟随错误，上一个选项文字变大了不会缩小等
![image](https://user-images.githubusercontent.com/30486512/121338036-b61ec000-c94f-11eb-8ac2-6a23be9f5700.png)
![image](https://user-images.githubusercontent.com/30486512/121338073-bf0f9180-c94f-11eb-92c4-cdd46ff5a5f8.png)
![image](https://user-images.githubusercontent.com/30486512/121338093-c33baf00-c94f-11eb-913d-a82f4e972d86.png)
`    @BindView(R.id.viewpager)
    ViewPager2 viewpager;
    @BindView(R.id.rectflow)
    TabVpFlowLayout  flowLayout;
    private FragmentManager fragmentManager = getSupportFragmentManager();
    private List<Fragment> mFragments = new ArrayList<>();
    private List<String> mTitle = Arrays.asList("领用", "退还", "借用", "归还", "变更", "调拨", "维修", "处置");
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        setContentView(R.layout.activity_fixed_bill_list);
        ButterKnife.bind(this);
        super.onCreate(savedInstanceState);
        Fragment fragment = new LYBliiList();
        mFragments.add(fragment);
        fragment = new THBliiList();
        mFragments.add(fragment);
        fragment = new JYBliiList();
        mFragments.add(fragment);
        fragment = new GHBliiList();
        mFragments.add(fragment);
        fragment = new BGBliiList();
        mFragments.add(fragment);
        fragment = new DBBliiList();
        mFragments.add(fragment);
        fragment = new WXBliiList();
        mFragments.add(fragment);
        fragment = new CZBliiList();
        mFragments.add(fragment);
        viewpager.setAdapter(new Fragment2Adapter(fragmentManager,getLifecycle(), mFragments));
        rectFlow();
    }

    private void rectFlow() {
        //设置数据，这里以 setAdapter 的形式
        flowLayout.setViewPager(viewpager);
        TabConfig config = new TabConfig.Builder()
                .setViewpager(viewpager)
                .setTextId(R.id.item_text)
                .setSelectedColor(Color.BLUE)
                .setUnSelectColor(getResources().getColor(R.color.unselect))
                .build();
        flowLayout.setAdapter(config,new TabFlowAdapter<String>(R.layout.item_msg, mTitle) {
            @Override
            public void onItemSelectState(View view, boolean isSelected) {
                super.onItemSelectState(view, isSelected);
                //选中时，可以改变不同颜色，如果你的background 为 selector，可以不写这个
                if (isSelected) {
                    setTextColor(view, R.id.item_text, Color.BLUE);
                } else {
                    setTextColor(view, R.id.item_text, getResources().getColor(R.color.unselect));
                }
            }

            @Override
            public void onItemClick(View view, String data, int position) {
                super.onItemClick(view, data, position);
                viewpager.setCurrentItem(position);
            }

            @Override
            public void bindView(View view, String data, int position) {
                /**
                 * 绑定数据，可以使用 setText(..) 等快捷方式，也可以视同 view.findViewById()
                 * 同时，当你的子控件需要点击事件时，可以通过  addChildrenClick() 注册事件，
                 * 然后重写 onItemChildClick(..) 即可拿到事件，否则就自己写。
                 * 自己的点击和长按不需要注册
                 */
                setText(view, R.id.item_text, data)
                        .setTextColor(view, R.id.item_text, getResources().getColor(R.color.unselect));

            }
        });

//        flowLayout.setViewPager(viewpager).setTextId(R.id.item_text)
//                .setSelectedColor(Color.BLUE)//必填，不然 Textview 没效果
//                .setUnSelectedColor(getResources().getColor(R.color.unselect));
    }`

**Comment by LillteZheng** [comment]
- 去掉 viewpager.setCurrentItem(position)，内部已经实现
- Fragment 懒加载，一些UI比较耗时的，放懒加载中使用
- ViewPager 缓存设置为3

**Comment by qingyinz** [comment]
使用懒加载效果没出现以上情况了

**Comment by qingyinz** [comment]
感谢
