### ISSUE TITLE
1.30版本怎么应用不了

### ISSUE THREAD

**Issue by yangqb** [LillteZheng/FlowHelper#25]
1.30版本怎么应用不了
Could not find com.github.LillteZheng.FlowHelper:tablibx:v1.30.

**Comment by LillteZheng** [comment]
试一下这个  implementation 'com.github.LillteZheng:FlowHelper:v1.30'

**Comment by yangqb** [comment]
换了地址可以了，谢谢

**Comment by yangqb** [comment]
> 试一下这个 implementation 'com.github.LillteZheng:FlowHelper:v1.30'

还有一个问题，我设置了tab_scale_factor，默认第0个选中，当我点击最后一个item的时候第0个没有缩放到原来的大小。（滑动viewPager时候缩放是没有问题的）

**Comment by LillteZheng** [comment]
不同的index才会有动画，逻辑如此
