### ISSUE TITLE
NestedscrollView内包LableFlowlayout，因为width不够在留下的空白区域无法进行滑动

### ISSUE THREAD

**Issue by Neroliuxx** [LillteZheng/FlowHelper#28]
如题所示，望解答，谢谢。

**Comment by LillteZheng** [comment]
贴图和代码哈

**Comment by Neroliuxx** [comment]
![1637889942(1)](https://user-images.githubusercontent.com/35095175/143513387-f24db103-1b44-4453-adbd-fff433743154.png)
代码就是很普通的父控件是NestedScrollView，子控件包含了多个LableFlowLayout，截图的这些空白区域应当是无法占满一行进行换行后留下的空白，无法在这些地发触发滑动操作，有数据的地方是可以的。

**Comment by LillteZheng** [comment]
这个确实没办法，LabelFlowLayout 会根据子控件去测量父布局的宽度，空白部分 不属于，LabelFlowLayout ，而是属于 NestedScrollView.
或者你可以在 labelFlowLayout 再套一层，再进行滑动

**Comment by YangShaoXiong** [comment]
看源码，作者在ScrollFlowLayout中的onTouchEvent方法做了事件拦截，所以会导致NestedScrollView无法滑动。可以考虑覆盖LabelFlowLayout中onTouchEvent方法来解决滑动冲突的问题，这种解决办法有没有什么后遗症还有待观察。期待作者提供完美解决方案
```
class FixedLabelFlowLayout @JvmOverloads constructor(
    context: Context, attrs: AttributeSet? = null
) : LabelFlowLayout(context, attrs) {

    override fun onTouchEvent(event: MotionEvent?): Boolean {
        return false
    }
}
```
