### ISSUE TITLE
Demo里结合Viewpager的示例中使用圆角矩形和资源res，初始设置的间距，在滑动回来后消失

### ISSUE THREAD

**Issue by xtgadw** [LillteZheng/FlowHelper#29]
![1](https://user-images.githubusercontent.com/18729346/144035035-fedf8c8f-460b-4178-a37d-55ff5f934ea9.png)

**Comment by LillteZheng** [comment]
控件与父布局吗？还是textView与背景？

**Comment by xtgadw** [comment]
你好，textView与背景。在demo第一条（TabFlowLayout结合Viewpager）中（第4个）可以复现这个问题。下面这两个属性在滑动后失效。（第5个跟父布局的间隙在滑动后也消失了）
<com.zhengsr.tablib.view.flow.TabVpFlowLayout
....
   app:tab_margin_l 
   app:tab_margin_r
...
/>

**Comment by LillteZheng** [comment]
更新到32即可
