### ISSUE TITLE
老哥，跑了下demo有几点问题想反馈下😂

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [LillteZheng/FlowHelper#31]
第一个是结合viewpager使用时点击指示器切换viewpager时卡卡的，还内存泄漏了😂

![微信图片_20220130203850](https://user-images.githubusercontent.com/54784104/151700188-e4a248b5-1dd8-4844-b42d-51fa151ccd0f.jpg)

第二个是竖直效果滑动recyclerview时左侧的TabFlowLayout经常不动，有时候rv还会闪现，还有rv空白的地方好像不能滑动😂

最后一个是支持显示更多的那个demo，收起时点击rv，也是会突然瞬移到看不见的地方😂

**Comment by SaltedFish-Extreme** [comment]
话说老哥有考虑过像MagicIndicator一样弄一个CommonNavigatorAdapter吗？这样我提取出来绑定adapter的扩展函数也方便😂
![image](https://user-images.githubusercontent.com/54784104/151703245-5ced746a-4924-4b2a-b99a-0a42968151f3.png)

**Comment by LillteZheng** [comment]
1. 内存泄露是 cusfragment 的问题，上层的问题，实际上库并没有内存泄露。
2. demo 卡是因为，viewpager 滑动时，所有的 tab 动画一起执行，比较消耗资源；可以单个测试
3. recyclerview 联动的，这个只是demo，实际上没花很大精力去优化体验，有个接口给到外部测试即可。
4. 更多的现象，我没太理解，demo只是显示 labelFlowLayout，没有rv ，如果你接入出现这个bug，可以单独提个issue
5. 目前不支持自定义 adapter，如果只是扩展函数，使用kotlin扩展会更方便一些

**Comment by SaltedFish-Extreme** [comment]
@LillteZheng 好吧😂我目前先用别人封装好的MagicIndicator，以后如果有需要会试试老哥的FlowHelper😉

**Comment by LillteZheng** [comment]
欢迎使用
