### ISSUE TITLE
LabelFlowLayout固定高度，内容超过高度后，滚动存在回跳的问题

### ISSUE THREAD

**Issue by zzzsssbo** [LillteZheng/FlowHelper#33]
https://user-images.githubusercontent.com/17812840/160771998-5f34d652-e1f9-468e-96e2-ccd4dc3ab6b5.mp4

**Comment by LillteZheng** [comment]
最近忙发布产品，五一后处理

**Comment by LillteZheng** [comment]
是有固定高度的需求吗？这个设计的时候，就是根据子控件的高度去计算父布局的高度的
