### ISSUE TITLE
TabFlowLayout 默认n后 在选择第 n-1 或者n+1个选择bug 

### ISSUE THREAD

**Issue by lwcloud** [LillteZheng/FlowHelper#4]
TabFlowLayout 默认n后 在选择第 n-1 或者n+1个选择bug 
和LabelFlowLayout如出一辙的问题

是这样的，由A界面进入B界面，B界面是用的TabFlowLayout ，在进入B界面我会根据用户先前保存的选择，进行回显默认选择，比如进入页面初始化TabFlowLayout后调用 flowLayout.setItemSelected(3);
这时候确是第3个标签是选中，但这时候去选择第2 或者第4个 tab的时候 mViewPager变了，但2 或者4的状态颜色不对，但选择其他后就正常了

**Comment by lwcloud** [comment]
注释掉 com.zhengsr.tablib.view.flow.TabFlowLayout 415行后正常
 //mAction.onItemClick(mLastIndex, position);

 private void chooseItem(int position, View view) {
        mLastIndex = mCurrentIndex;
        mCurrentIndex = position;
        if (mViewPager != null && mAction != null) {
            mLastIndex = mAction.getCurrentIndex();
        }
        if (mAction != null) {
            //mAction.onItemClick(mLastIndex, position);//修改这里后正常了，不知道有啥后遗症没？
        }
        if (mAdapter != null) {
            mAdapter.onItemClick(view, mAdapter.getDatas().get(position), position);
        }
        /**
         * 如果没有 viewpager，则需要使用 scroller 平滑过渡
         */
        if (mViewPager == null) {
            updateScroll(view,true);
            invalidate();
        }
    }

**Comment by LillteZheng** [comment]
setItemSelected 这个方法是转发给 竖直方向的，用来跟recyclerview 联动的，如果要选择默认位置，还是使用 setViewPager(x,x,2,x,x); 这个方法呢；
后面我再整理一下

**Comment by lwcloud** [comment]
用这个方法 setViewPager(x,x,2,x,x);我没有试，但感觉可以，但就算可以，那也太不方便了，还得去获取对应的mViewPager

**Comment by LillteZheng** [comment]
参考最新的吧，感谢反馈
  /**
   * @ setViewPager 设置 viewpager
   * @ setTextId  view 中 textview 的id,用于TextView的颜色变化
   * @ setDefaultPosition 默认选中的item，初始值为0，也可以从第二页或者其他 位置
   * @ setSelectedColor //选中的颜色，如果为 TabColorTextView 不需要些这个
   * @ setUnSelectedColor //没有选中的颜色，如果为 TabColorTextView 不需要些这个
   */
 flowLayout.setViewPager(mViewPager)
            .setTextId(R.id.item_text) 
            .setSelectedColor(Color.WHITE) 
            .setUnSelectedColor(getResources().getColor(R.color.unselect)) 
            .setDefaultPosition(2);
