### ISSUE TITLE
在ViewPager中嵌套, 滑动不行

### ISSUE THREAD

**Issue by LillteZheng** [LillteZheng/FlowHelper#5]
在ViewPager中嵌套, 滑动不行

_Originally posted by @748297973 in https://github.com/LillteZheng/FlowHelper/issues/1#issuecomment-595334011_

**Comment by LillteZheng** [comment]
应该是事件分发问题，可以把问题描述清楚一点；

**Comment by 748297973** [comment]
在ViewPager包含的fragment中使用,可以在本控件上点击使他滚动,但是左右滑动直接滑动到另一个页面了

**Comment by 748297973** [comment]
> 应该是事件分发问题，可以把问题描述清楚一点；

在ViewPager包含的fragment中使用,可以在本控件上点击使他滚动,但是左右滑动直接滑动到另一个页面了

**Comment by LillteZheng** [comment]
额，还是不太明白你的问题；你在 viewpager 的 fragment 使用 tabflowlayout ？，然后滑动 viewpager 到另外的页面？

**Comment by 748297973** [comment]
> 额，还是不太明白你的问题；你在 viewpager 的 fragment 使用 tabflowlayout ？，然后滑动 viewpager 到另外的页面？

链接：https://pan.baidu.com/s/1nAnPOLan0jFpG6bRUsc19w 
提取码：6c63

**Comment by LillteZheng** [comment]
嗯，看你的意思是点击是可以，滑动的时候，事件被 viewpager 截取了是吧，我明天看看，我记得滑动的时候，是屏蔽 父控件的事件的

**Comment by 748297973** [comment]
> 嗯，看你的意思是点击是可以，滑动的时候，事件被 viewpager 截取了是吧，我明天看看，我记得滑动的时候，是屏蔽 父控件的事件的

好的

**Comment by LillteZheng** [comment]
已解决，更新到最新的即可，感谢反馈
