### ISSUE TITLE
吧错误log打上来吧

### ISSUE THREAD

**Issue by 748297973** [LillteZheng/FlowHelper#7]
吧错误log打上来吧

_Originally posted by @LillteZheng in https://github.com/LillteZheng/FlowHelper/issues/6#issuecomment-596349315_

# T-connStch(2)

java.lang.RuntimeException

Cannot make calls to a recycled instance!

解析原始
1 android.content.res.TypedArray.getResources(TypedArray.java:157)
2 android.content.res.XResources$XTypedArray.getDimensionPixelSize(XResources.java:1344)
3 com.zhengsr.tablib.view.action.BaseAction.void autoScaleView()(Unknown Source:3)
4 ##_parent_##10##_parent_##
5 ##_child_## void chooseIndex(int,int)##_child_##
6 ##_child_## void chooseSelectedPosition(int)##_child_##
7 ##_child_## void config(com.zhengsr.tablib.view.flow.TabFlowLayout)##_child_##
8 ##_child_## void configAttrs(android.content.res.TypedArray)##_child_##
9 ##_child_## void doAnim(int,int,int)##_child_##
10 ##_child_## void draw(android.graphics.Canvas)##_child_##
11 ##_child_## com.zhengsr.tablib.bean.TabValue getValue(android.view.View)##_child_##
12 ##_child_## void setBean(com.zhengsr.tablib.bean.TabBean)##_child_##
13 ##_child_## com.zhengsr.tablib.view.action.BaseAction setViewPager(androidx.viewpager.widget.ViewPager)##_child_##
14 ##_child_## void valueChange(com.zhengsr.tablib.bean.TabValue)##_child_##
15 com.zhengsr.tablib.view.action.RoundAction.void config(com.zhengsr.tablib.view.flow.TabFlowLayout)(Unknown Source:0)
16 ##_parent_##4##_parent_##
17 ##_child_## void configAttrs(android.content.res.TypedArray)##_child_##
18 ##_child_## void draw(android.graphics.Canvas)##_child_##
19 ##_child_## void setBean(com.zhengsr.tablib.bean.TabBean)##_child_##
20 ##_child_## void valueChange(com.zhengsr.tablib.bean.TabValue)##_child_##
21 com.zhengsr.tablib.view.flow.TabFlowLayout.boolean access$100(com.zhengsr.tablib.view.flow.TabFlowLayout)(Unknown Source:63)
22 ##_parent_##2##_parent_##
23 ##_child_## boolean access$802(com.zhengsr.tablib.view.flow.TabFlowLayout,boolean)##_child_##
24 ##_child_## void chooseTabTpye(int)##_child_##
25 com.zhengsr.tablib.view.flow.TabFlowLayout.void access$000(com.zhengsr.tablib.view.flow.TabFlowLayout)(Unknown Source:10)
26 ##_parent_##9##_parent_##
27 ##_child_## boolean access$102(com.zhengsr.tablib.view.flow.TabFlowLayout,boolean)##_child_##
28 ##_child_## void access$600(com.zhengsr.tablib.view.flow.TabFlowLayout,android.view.View,boolean)##_child_##
29 ##_child_## void access$900(com.zhengsr.tablib.view.flow.TabFlowLayout,int,android.view.View)##_child_##
30 ##_child_## void chooseItem(int,android.view.View)##_child_##
31 ##_child_## void configClick(android.view.View,int)##_child_##
32 ##_child_## boolean isLabelFlow()##_child_##
33 ##_child_## com.zhengsr.tablib.view.flow.TabFlowLayout setDefaultPosition(int)##_child_##
34 ##_child_## com.zhengsr.tablib.view.flow.TabFlowLayout setTabBean(com.zhengsr.tablib.bean.TabBean)##_child_##
35 ##_child_## void updateScroll(android.view.View,boolean)##_child_##
36 com.movies.k8.fragment.HomeTabMovies.void access$100(com.movies.k8.fragment.HomeTabMovies)(Unknown Source:210)
37 ##_parent_##3##_parent_##
38 ##_child_## java.lang.String access$302(com.movies.k8.fragment.HomeTabMovies,java.lang.String)##_child_##
39 ##_child_## void inView(android.view.View)##_child_##
40 ##_child_## void loadMore(com.movies.k8.bean.HomeCategoryBean)##_child_##
41 com.movies.k8.fragment.HomeTabMovies.me.bakumon.statuslayoutmanager.library.StatusLayoutManager access$000(com.movies.k8.fragment.HomeTabMovies)(Unknown Source:0)
42 ##_parent_##7##_parent_##
43 ##_child_## java.lang.String access$202(com.movies.k8.fragment.HomeTabMovies,java.lang.String)##_child_##
44 ##_child_## void initView(android.view.View)##_child_##
45 ##_child_## void lambda$loadDone$0(com.github.nukc.LoadMoreWrapper.LoadMoreAdapter$Enabled)##_child_##
46 ##_child_## void loadDone(com.movies.k8.bean.HomeCategoryBean)##_child_##
47 ##_child_## void loadError()##_child_##
48 ##_child_## com.movies.k8.fragment.HomeTabMovies newInstance(int,java.lang.String)##_child_##
49 ##_child_## void onRefresh(com.scwang.smartrefresh.layout.api.RefreshLayout)##_child_##
50 com.movies.k8.fragment.BaseFragment.onCreateView(Unknown Source:17)
51 androidx.fragment.app.Fragment.performCreateView(Unknown Source:15)
52 androidx.fragment.app.FragmentManagerImpl.moveToState(Unknown Source:684)
53 androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source:105)
54 androidx.fragment.app.FragmentManagerImpl.moveToState(Unknown Source:46)
55 androidx.fragment.app.BackStackRecord.executeOps(Unknown Source:177)
56 androidx.fragment.app.FragmentManagerImpl.executeOps(Unknown Source:38)
57 androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(Unknown Source:114)
58 androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(Unknown Source:88)
59 androidx.fragment.app.FragmentManagerImpl.execSingleAction(Unknown Source:31)
60 androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(Unknown Source:6)
61 androidx.fragment.app.FragmentPagerAdapter.finishUpdate(Unknown Source:4)
62 androidx.viewpager.widget.ViewPager.populate(Unknown Source:385)
63 androidx.viewpager.widget.ViewPager.populate(Unknown Source:2)
64 androidx.viewpager.widget.ViewPager.onMeasure(Unknown Source:194)
65 android.view.View.measure(View.java:23389)
66 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6770)
67 android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
68 android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
69 android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
70 android.view.View.measure(View.java:23389)
71 androidx.viewpager.widget.ViewPager.onMeasure(Unknown Source:239)
72 android.view.View.measure(View.java:23389)
73 android.widget.LinearLayout.measureVertical(LinearLayout.java:978)
74 android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
75 android.view.View.measure(View.java:23389)
76 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6770)
77 android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
78 androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:156)
79 android.view.View.measure(View.java:23389)
80 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6770)
81 android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
82 android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
83 android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
84 android.view.View.measure(View.java:23389)
85 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6770)
86 android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
87 android.view.View.measure(View.java:23389)
88 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6770)
89 android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
90 android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
91 android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
92 android.view.View.measure(View.java:23389)
93 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6770)
94 android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
95 com.android.internal.policy.DecorView.onMeasure(DecorView.java:717)
96 android.view.View.measure(View.java:23389)
97 android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3064)
98 android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1881)
99 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2173)
100 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1769)
101 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
102 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1312)
103 android.view.Choreographer.doCallbacks(Choreographer.java:1123)
104 android.view.Choreographer.doFrame(Choreographer.java:941)
105 android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:1227)
106 android.os.Handler.dispatchMessage(Handler.java:106)
107 android.os.Looper.loop(Looper.java:193)
108 android.app.ActivityThread.main(ActivityThread.java:7009)
109 java.lang.reflect.Method.invoke(Native Method)
110 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
111 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by LillteZheng** [comment]
你这个看不出来啊，使用 error 和 androidruntime 过滤一下呢

**Comment by 748297973** [comment]
> 你这个看不出来啊，使用 error 和 androidruntime 过滤一下呢

bugly上传的,我也没法复现,不是我用的导致的

**Comment by LillteZheng** [comment]
刚才看了以下 自定义属性，都是有加是否回收的判断。你用 bugly 定位一下具体哪行呢
