### ISSUE TITLE
TabFlowLayout 当有2个，3个，4个tab时，怎么布局均分并填充

### ISSUE THREAD

**Issue by AndMy** [LillteZheng/FlowHelper#8]
TabFlowLayout 当有2个，3个，4个tab时，怎么布局均分并填充
<com.zhengsr.tablib.view.flow.TabFlowLayout
        android:id="@+id/tabFlow"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>
TabFlowLayout宽度 当为match_parent时，item宽度也为match_parent时，会导致每个item填充
TabFlowLayout宽度 当为wrap_content时，会显示所有的item，但是不会填充
哪个属性可以均分并填充布局

**Comment by LillteZheng** [comment]
后面弄一下

**Comment by AndMy** [comment]
好

**Comment by LillteZheng** [comment]
更新一下，使用 tab_visual_count (可视化个数，比如有一排，我们就只要显示4个，此时宽度均分)就可以了
