### ISSUE TITLE
有时候setVisualCount无效

### ISSUE THREAD

**Issue by prohack** [LillteZheng/FlowHelper#9]
我用了您的CusBFragmentUtil配合使用的情况下 第一个被加载的fragment使用TabFlowLayout和viewpager是正常的，但是第二个fragment就会出现TabFlowLayout的tab显示异常 变成xml里原本的宽度了。

比如xml中是match_parent则会一屏只有一个tab，wrap_content就是tab全部粘在一起，但是我确定两个fragment代码都是一样的 均有在xml中配置TabFlowLayout的VisualCount 但是第二个fragment就是不正常 我尝试了在java代码中手动调用setVisualCount并且invalidate仍然不生效，有好的解决方案嘛

**Comment by LillteZheng** [comment]
cusBFragmentUtil 是测试用的，很多不玩啥那，可以使用 https://github.com/YoKeyword/Fragmentation 这个库；然后fragment + tabflow de ,可以参考我的 wanandroid 这个工程 https://github.com/LillteZheng/WanAndroid，里面也有实例，比如project和微信的
